<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Strona Powitalna</title>
</head>
<body>

<h1>
    Witaj uzytkowniku o imieniu ${name}
</h1>
<h2>Salary: ${salary!"Salary undefined"}</h2>

</body>
</html>